baseurl = "https://estatutos.glud.org"
title = "Estatutos GLUD"
author = "Grupo GNU/Linux de la Universidad Distrital"
canonifyurls = true
languagecode = "es"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Estatutos GLUD"
  disableWebFonts = false
  actual = "estatutos/estatutos-20110712.md" #estatutos actuales para la página principal

[[menu.main]]
    name = "Actuales" 
    url  = "/estatutos/actuales"

[[menu.main]]
    name = "Acerca" 
    url  = "/acerca"

[[menu.main]]
    name = "Archivo"
    url  = "/estatutos"
    
[[menu.main]]
    name = "Página oficial GLUD"
    url  = "https://glud.udistrital.edu.co/"

